import { animeService } from './anime-service.js?v=20260813-3';
const grid=document.querySelector('#animeGrid'), status=document.querySelector('#status'), title=document.querySelector('#resultsTitle'), count=document.querySelector('#resultsCount'), form=document.querySelector('#searchForm'), input=document.querySelector('#searchBar'), dialog=document.querySelector('#detailsDialog'), detail=document.querySelector('#detailsContent');
const fallback='data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="400" height="600"%3E%3Crect width="100%25" height="100%25" fill="%23292929"/%3E%3Ctext x="50%25" y="50%25" fill="%23b6afaa" font-family="Arial" font-size="28" text-anchor="middle"%3ENo poster%3C/text%3E%3C/svg%3E';
function text(el,value){ el.textContent=value; return el; }
function poster(anime){ const image=document.createElement('img'); image.className='poster'; image.loading='lazy'; image.alt=`Poster for ${anime.title}`; image.src=anime.image||fallback; image.addEventListener('error',()=>{image.src=fallback;},{once:true}); return image; }
function render(list){ grid.replaceChildren(); count.textContent=`${list.length} result${list.length===1?'':'s'}`; list.forEach(anime=>{ const card=document.createElement('article'); card.className='anime-card'; card.append(poster(anime)); const copy=document.createElement('div'); copy.className='card-copy'; const h2=document.createElement('h2'); text(h2,anime.title); const meta=document.createElement('p'); meta.className='meta'; text(meta,[anime.year,anime.type].filter(Boolean).join(' · ')||'Anime'); const button=document.createElement('button'); button.type='button'; button.className='details-button'; text(button,'View details'); button.addEventListener('click',()=>showDetails(anime)); copy.append(h2,meta,button); card.append(copy); grid.append(card); }); }
function showDetails(anime){ detail.replaceChildren(); const layout=document.createElement('div'); layout.className='detail-layout'; layout.append(poster(anime)); const copy=document.createElement('div'); const h2=document.createElement('h2'); h2.id='detailTitle'; text(h2,anime.title); const meta=document.createElement('p'); meta.className='detail-meta'; text(meta,[anime.year,anime.type,anime.status].filter(Boolean).join(' · ')||'Anime'); const description=document.createElement('p'); description.className='detail-description'; text(description,anime.synopsis); copy.append(h2,meta,description); if(anime.crunchyrollUrl){ const link=document.createElement('a'); link.className='watch-link'; link.href=anime.crunchyrollUrl; link.target='_blank'; link.rel='noopener noreferrer'; text(link,'Watch on Crunchyroll ↗'); copy.append(link); }else { const searchButton=document.createElement('button'); searchButton.type='button'; searchButton.className='watch-link'; text(searchButton,'Copy title & search Crunchyroll ↗'); searchButton.addEventListener('click',()=>{ navigator.clipboard?.writeText(anime.title).catch(()=>{}); window.open('https://www.crunchyroll.com/search','_blank','noopener'); }); const note=document.createElement('p'); note.className='unavailable'; text(note,'Paste the copied title into Crunchyroll search. Availability varies by region.'); copy.append(searchButton,note); } layout.append(copy); detail.append(layout); dialog.showModal(); }
async function load(query=''){ status.className='status'; text(status,'Loading anime…'); grid.replaceChildren(); try { const results=query ? await animeService.search(query) : await animeService.popular(); title.textContent=query ? `Results for “${query}”` : 'Popular anime'; if(!results.length){ text(status,'No anime matched that search. Try a different title.'); count.textContent='0 results'; return; } text(status,''); render(results); } catch(error) { count.textContent=''; status.className='status error'; text(status,error.message); } }
form.addEventListener('submit',event=>{ event.preventDefault(); const query=input.value.trim(); load(query); }); document.querySelector('#dialogClose').addEventListener('click',()=>dialog.close()); dialog.addEventListener('click',event=>{ if(event.target===dialog) dialog.close(); }); load();
